### ISSUE TITLE
Initialise the Django backend

### ISSUE THREAD

**Issue by ThaveeshaDheerasekera** [ThaveeshaDheerasekera/circle-server#1]
## Todo

- [x] Initialise the project
- [x] Create Dockerfile
- [x] Create docker-compose file
- [x] Create the core app
- [x] Create the model
- [x] Makemigrations
- [x] Migrate Database
- [x] Create getAll API call
- [x] Create createNote call
- [x] Create the auth app
